### PR TITLE
Generics!

### LINKED ISSUE #20: Generics support
Currently Messenger allows to specify msg type for the protocol by reflection, so that it can construct and give the user already deserialized messages. Since go1.18 there is support for generics which can be used for this specific case instead of generics.

### PR DESCRIPTION
**Pull request by Wondertan**
~~I liked the experience with generics so far,~~(I actually don't anymore, there is many limits in its current state - no generic type embedding, inability to instantiate a generic value, etc) and this change makes so much sense to improve the usability dev ux of the Messanger. ~~The only thing is that generics are still a bit raw, and there is still a place where reflection is not avoidable, unfortunately, but this should change in future releases.~~ There is a solution for this now - through a constructor on the Message interface

Closes #20

### CODE REVIEW

**Review by liamsi — APPROVED** [review]
Cool!

**Comment by liamsi** [comment]
Do you mind adding other reviewers from the node team instead of me here?

**Comment by Wondertan** [comment]
Yes, but nothing really changed here besides rebase on the deps updates

**Comment by Wondertan** [comment]
Pushed the final state of generics without any reflection involved 🎉 

Kudos to @tzdybal for the idea with `New`

**Comment by adlerjohn** [comment]
Is this one ready for review?

**Comment by Wondertan** [comment]
@adlerjohn, do you want to take a look? 😁

**Comment by adlerjohn** [comment]
Yes 😂 but also wondering if this is still in draft or if it's ready.

**Comment by Wondertan** [comment]
@adlerjohn, yes! I would love to hear your 5 cents here.

**Pull request merged**
